spring.application.name=user-management

# PostgreSQL
spring.datasource.url=jdbc:postgresql://localhost:5432/user_management
spring.datasource.username=user_management_user
spring.datasource.password=user_management_password

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Server
server.port=8080
